# This prints the background SQL to your console so you can see what Spring is doing
spring.jpa.show-sql=true

# This enables a web interface for your H2 database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:performancedb